### ISSUE TITLE
Does this sample contain the progressive profiling feature?

### ISSUE THREAD

**Issue by danijam** [Azure-Samples/active-directory-external-identities-woodgrove-demo#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> 

### Versions
>

### Mention any other details that might be useful
Hi, I'm trying to setup Azure B2C with the requirement that I want to collect additional user data on subsequent logins. I've see this demoed here: https://youtu.be/GmBKlXED9Ug?t=433 and wondered if this demo has it also? I can't find any reference to it in this repo. Any help regarding how to get started with the progressive profiling feature will be much appreciated.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ArieJones** [comment]
I am actually trying to find more information on the same thing. If this demo code does not have an example can you point me in the right direction to one that does?

**Comment by danijam** [comment]
@ArieJones I got a response here: https://github.com/azure-ad-b2c/samples/issues/57

**Comment by ArieJones** [comment]
Awesome! Thanks @danijam !
