### ISSUE TITLE
Redundant Labels for Password and Email

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-external-identities-woodgrove-demo#2]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- visit page

### Any log messages given by the failure
none

### Expected/desired behavior
no redundant labels for email and password

![image](https://user-images.githubusercontent.com/14079228/40930661-47aac262-67f6-11e8-8b00-5553d1aef19d.png)

Angular Material Design Example
![material design input fields](https://user-images.githubusercontent.com/14079228/40930743-8be00ad2-67f6-11e8-8a7b-7561d2dac5b5.gif)

----

Looks really good btw!! 👍👍

**Comment by chrispadgettlivecom** [comment]
This is fixed in https://github.com/Azure-Samples/active-directory-external-identities-woodgrove-demo/pull/3.

**Comment by spottedmahn** [comment]
that's great!
