### ISSUE TITLE
Sign in with your personal account using an A/B policy (preview) Error

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-external-identities-woodgrove-demo#4]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- visit https://woodgrovegroceriesb2c.azurewebsites.net/Account/LogIn
- click on `Sign in with your personal account using an A/B policy (preview)`

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/14079228/47060437-8e292f80-d19b-11e8-9df8-8d50e351a764.png)

### Expected/desired behavior
No error

**Comment by chrispadgettlivecom** [comment]
Thank you, @spottedmahn, I believe this A/B feature is changing so I'll remove it from the front-end app for now.
